nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:4200','*'] # Origine de votre frontend Angular
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS','PATCH']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: ['Authorization']
    max_age: 3600
    allow_credentials: true
  paths:
    '^/api/': # Appliquer les règles CORS uniquement sur vos endpoints API
      allow_origin: ['http://localhost:4200','*']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS','PATCH']
      allow_headers: ['Content-Type', 'Authorization']
      max_age: 3600
